# This file provides instructions for packaging.

`Sort-Key-Top-PP`
	deps:test-requirement    [ deps:on "Test::More 0.96"^^deps:CpanId ];
	deps:runtime-requirement [ deps:on "Exporter::Shiny"^^deps:CpanId ];
	deps:runtime-requirement [ deps:on "perl 5.008"^^deps:CpanId ].

