# This file provides instructions for packaging.

`Sort-Key-Top-PP`
	perl_version_from m`Sort::Key::Top::PP`;
	version_from      m`Sort::Key::Top::PP`;
	readme_from       m`Sort::Key::Top::PP`;
	test_requires     p`Test::More 0.61`;
	requires          p`Exporter::Everything`;
	.

